// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type NewUser struct {
	UID        string  `json:"uid"`
	Username   string  `json:"username"`
	FirstName  string  `json:"firstName"`
	MiddleName *string `json:"middleName"`
	LastName   *string `json:"lastName"`
}

type User struct {
	UID        string  `json:"uid"`
	Username   string  `json:"username"`
	FirstName  string  `json:"firstName"`
	MiddleName *string `json:"middleName"`
	LastName   *string `json:"lastName"`
}
